doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options:
                username: '%env(resolve:MONGODB_USER)%'
                password: '%env(resolve:MONGODB_PASS)%'
                authSource: '%env(resolve:MONGODB_AUTH_DB)%'
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/src/Infrastructure/Persistence/odm/mapping'
                    prefix: 'App\Domain'

