version: '3.8'

services:
    simple_app_mongo:
        container_name: simple_app_mongo
        build: docker-build/mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: simple_app
            MONGO_INITDB_ROOT_PASSWORD: simple_app
        ports:
            - 27017:27017
        networks:
            - simple_app_network

    simple_app_php:
        container_name: simple_app_php
        build:
            context: docker-build/php
        volumes:
            - ./:/app/simple-app
        networks:
            - simple_app_network

    simple_app:
        container_name: simple_app
        build:
            context: docker-build/nginx
        volumes:
            - ./:/app/simple-app
        depends_on:
            - simple_app_php
            - simple_app_mongo
        ports:
            - "80:80"
            - "443:443"
        networks:
            - simple_app_network

networks:
    simple_app_network:
